char* op_names[] =
{
    ['+']  = "ADD",
    ['-']  = "SUB",
    ['*']  = "MULT",
    ['/']  = "DIV",
    ['%']  = "MOD",
    ['!']  = "NOT",
    ['`']  = "GT ",
    ['>']  = "PCR",
    ['<']  = "PCL",
    ['^']  = "PCU",
    ['v']  = "PCD",
    ['?']  = "PCRAND",
    ['_']  = "HIF",
    ['|']  = "VIF",
    ['"']  = "STRING",
    [':']  = "DUP",
    ['\\'] = "SWAP",
    ['$']  = "POPR",
    ['.']  = "POPI",
    [',']  = "POPC",
    ['#']  = "BRIDGE",
    ['g']  = "GET",
    ['p']  = "PUT",
    ['&']  = "READI",
    ['~']  = "READC",
    ['@']  = "END",
    [' '] = "NOOP",
    [';']  = "IGNORE",

    [29] = "LEFT",
    [30] = "RIGHT",
    [31] = "UP",
    [32] = "DOWN",
    [33] = ""
};
